Hw1
Tetiana-KH/js_tkhorosha pull request #2
Opened 2023-09-08 14:54 UTC by Tetiana-KH

2023-09-08 18:27 UTC, adudyak requested changes

2023-09-08 18:27 UTC, adudyak commented on pages/checkout.js
move content of checkout page to cart page, then delete this file

2023-09-08 18:27 UTC, adudyak commented on pages/cart.js
> +    return parseFloat(priceString.replace(/[^0-9.-]/g, ''));
why do you need `-` in regex? only digits, dots and maybe comma is enough.

2023-09-08 18:27 UTC, adudyak commented on pages/cart.js
> +  async getDelivery() {
this method is not used in scenario

2023-09-08 18:27 UTC, adudyak commented on pages/cart.js
> +  verifySuccessfulPurchase() {
this method is not used in scenario

2023-09-08 18:27 UTC, adudyak commented on pages/success.js
move content to cart page and delete this file

2023-09-08 18:27 UTC, adudyak commented on pages/success.js
> +    I.amOnPage('/index.php?route=checkout/success');
you should not navigate to success page, website should navigate you

2023-09-08 18:27 UTC, adudyak commented on pages/success.js
> +    I.click(this.successContinueButton);
remove. method name should correspond to it's instructions. Navigation does not verify success

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +    productPage.addToCart();
`addToCart();` method proceeds to cart page, but next step is grabbing of price, color, size, which are not available in cart page.
Grab prices, then add to cart and proceed to checkout

2023-09-08 18:27 UTC, adudyak commented on pages/product.js
> +  addToCart() {
this method, according to name, should only add to cart, but it is also proceeds to shopping cart. Move extra functionality to other method.

2023-09-08 18:27 UTC, adudyak commented on pages/product.js
> +    I.click(this.shoppingCartButton);
you need to open checkout page, not shopping cart one

2023-09-08 18:27 UTC, adudyak commented on steps_file.js
> +    this.amOnPage('/index.php?route=product/product&product_id=44');
remove this line. does not correspond to method name and navigation to specific page should be done in separate method or in scenario

2023-09-08 18:27 UTC, adudyak commented on steps_file.js
> +  proceedToCheckOut() {
move this to cart page.
name it `fillCheckoutForm()`

2023-09-08 18:27 UTC, adudyak commented on steps_file.js
> +    this.click(confirmOrderButton);
you need to grab total price, tax before confirming an order

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +const { totalPrice1 } = require("../pages/checkout");
remove lines 1-4

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +//});
uncomment login here, and remove it in scenario

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +    I.assertEqual(subTotal + flatShippingRate, totalPrice1, "Prices are not in match!");
`totalPrice` extracted, `totalPrice1` used

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +    I.assertEqual(subTotal + flatShippingRate, totalPrice1, "Prices are not in match!");
`flatShippingRate` is not grabbed

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +    I.amOnPage('http://opencart.qatestlab.net/index.php?route=checkout/cart');
proceed to checkout via buttons in cart.js

2023-09-08 18:27 UTC, adudyak commented on tests/buyProduct_test.js
> +Scenario('buy product', async ({ I, cartPage, productPage, checkoutPage, successPage }) => {
update scenario to perform instructions in following order:

1. Open product.
2. Select size, color. Grab productPrice: product + color + size.
3. Add product to cart
4. Open checkout
5. Proceed to last step
6. Grab totalPrice, tax
7. Compare productPrice + tax with totalPrice
8. Complete order
9. Verify successful message is displayed

2023-09-08 18:33 UTC, adudyak requested changes

2023-09-08 18:33 UTC, adudyak commented on pages/success.js
> +    const regTitleText = 'Your order has been placed!';
you are using UA text to verify login, but EN to verify purchase.
Add language selection in case site shows language randomly.

2023-09-10 19:23 UTC, adudyak requested changes

2023-09-10 19:23 UTC, adudyak commented on codecept.conf.js
> +    checkoutPage: "./pages/checkout.js",
remove

2023-09-10 19:23 UTC, adudyak commented on pages/cart.js
> +    I.assertEqual(subTotal + flatShippingRate, totalPrice, "Prices are not in match!");
remove, assert should be only in scenario

2023-09-10 19:23 UTC, adudyak commented on pages/cart.js
> +    I.waitForVisible('//*[@id="modal-shipping"]/div/div/div[2]/div/label', 5);
move locator to top

2023-09-10 19:23 UTC, adudyak commented on pages/cart.js
> +    const totalPrice = await cartPage.getTotalPrice();
remove

2023-09-10 19:23 UTC, adudyak commented on pages/cart.js
> +    return this.parsePrice(await I.grabTextFrom(this.subTotalPrice)) + this.parsePrice(await I.grabTextFrom(this.flatShippingRate));
during checkout process:
grab shipping rate and return it to scenario, where add to product price + color + price:
![image](https://github.com/Tetiana-KH/js_tkhorosha/assets/19595492/82ad4117-4639-4ff5-8daf-3fc807959f65)
then compare your calculations to bottom price:
![image](https://github.com/Tetiana-KH/js_tkhorosha/assets/19595492/f9f2f816-0032-4745-8104-abacd86408a7)

2023-09-10 19:23 UTC, adudyak commented on tests/buyProduct_test.js
> +  I.assertEqual(subTotal + flatShippingRate, totalPrice, "Prices are not in match!");
I don't see grabbing of flatShippingRate, you are using locator from cart page

2023-09-10 19:23 UTC, adudyak commented on tests/buyProduct_test.js
> +const { subTotal, flatShippingRate } = require("../pages/cart");
remove

2023-09-10 19:23 UTC, adudyak commented on tests/buyProduct_test.js
> +const steps_file = require("../steps_file");
remove

2023-09-10 19:23 UTC, adudyak commented on steps_file.js
> +const { pause } = require("codeceptjs");
remove

2023-09-10 19:23 UTC, adudyak commented on steps_file.js
> +const { billingDetailsDropDown, newAddressRadioButton, firstName, lastName, address1, city, postCode, country, stateOption, confirmOrderButton } = require("./pages/cart");
remove

2023-09-10 19:23 UTC, adudyak commented on steps_file.js
> +const { myAccountSpoiler, shoppingCartButton } = require("./pages/product");
remove

2023-09-10 19:23 UTC, adudyak commented on steps_file.js
> +const { languageSelectDropDown, selectEnglishButton } = require("./pages/account");
it is strange, that you store locators, which only used here, in other object.
move them here, as the ones below

2023-09-10 19:23 UTC, adudyak commented on steps_file.js
> +email = { css: "#input-email" };
add `const` to variables, these are not object keys

2023-09-10 19:27 UTC, adudyak requested changes

2023-09-10 19:27 UTC, adudyak commented on tests/buyProduct_test.js
> +  productPage.addToCart();
add product to cart and open cart before extracting totalPrice from cart. Currently it is vice versa

2023-09-11 09:44 UTC, Tetiana-KH commented on pages/cart.js
> +    return this.parsePrice(await I.grabTextFrom(this.subTotalPrice)) + this.parsePrice(await I.grabTextFrom(this.flatShippingRate));
Not sure if I've done this correctly

2023-09-11 17:29 UTC, adudyak requested changes

2023-09-11 17:29 UTC, adudyak commented on pages/cart.js
> +  async getTotalPrice() {
you already have method with same name

2023-09-11 17:29 UTC, adudyak commented on tests/buyProduct_test.js
> +Scenario('buy product', async ({ I, cartPage, productPage, successPage }) => {
please check navigation order

2023-09-11 17:38 UTC, Tetiana-KH commented on pages/cart.js
> +  async getTotalPrice() {
removed this duplicate

2023-09-11 17:42 UTC, Tetiana-KH commented on tests/buyProduct_test.js
> +Scenario('buy product', async ({ I, cartPage, productPage, successPage }) => {
corrected in the following order: I, productPage, cartPage, successPage

2023-09-12 17:01 UTC, adudyak requested changes

2023-09-12 17:01 UTC, adudyak commented on pages/cart.js
> +    I.click(this.confirmOrderButton);
move this line to separate method and call after comparing prices

2023-09-12 17:01 UTC, adudyak commented on pages/product.js
> +    return this.parsePrice(await I.grabTextFrom(this.productPriceText)) + this.parsePrice(await I.grabTextFrom(this.colorOption)) + this.parsePrice(await I.grabTextFrom(this.sizeOption)) + this.parse
remove everything after size, it is not available at product page

2023-09-12 17:01 UTC, adudyak commented on tests/buyProduct_test.js
> +  const flatShippingRate = await cartPage.getFlatShippingRate();
`flatShippingRate` is equal to `NaN`. Check locator

2023-09-12 17:01 UTC, adudyak commented on tests/buyProduct_test.js
> +  const totalPrice = await cartPage.getTotalPrice();
`totalPrice` is `220`, but should be `225` for product 48. Check locator

2023-09-13 15:51 UTC, adudyak approved these changes

2023-09-13 15:51 UTC, adudyak commented on pages/cart.js
> +  checkOutButton: { xpath: '//ul[@id="cart"]//li/div/a[contains(text(), "Checkout")]' },
this locator failed for me, try simple version:
`'//div/a[contains(text(), "Checkout")]'`

2023-09-13 15:58 UTC, Tetiana-KH commented on pages/cart.js
> +  checkOutButton: { xpath: '//ul[@id="cart"]//li/div/a[contains(text(), "Checkout")]' },
Updated

2023-09-13 16:00 UTC, merged